server:
  port: 8080

spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: bookserver
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.jvglpxrqqpnmmqzdfiqj
    password: ${SUPABASE_DB_PASSWORD} # 로컬 환경변수(SUPABASE_DB_PASSWORD)로 주입하세요. (Git 노출 방지)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
